version: '3'

services:
  proxy:
    container_name: proxy
    image: nginx:1.26.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./letsencrypt/certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www
      - ./logs/:/var/log/nginx/
    # networks:
    #   - ${DOCKER_VPN}

networks:
  default:
    external:
      name: ${DOCKER_VPN}