version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: portainerce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - ${DOCKER_VPN}

networks:
  default:
    external:
      name: ${DOCKER_VPN}